# =============================================================================
# modules/key-vault/main.tf
# =============================================================================
# Per-environment Azure Key Vault using RBAC permission model.
# Placeholder secrets are created with null values — a human must populate
# them before running terraform apply in an environment that needs them.
#
# Secrets managed here:
#   ado-pat               - Azure DevOps PAT for agent registration (cloud-init)
#   acr-admin-password    - ACR admin password (only if admin_enabled = true on ACR)
#   vm-admin-password     - Agent VM local admin password (generated by agent-vm module)
# =============================================================================

locals {
  name_suffix = "snowtee-${var.env}-eus-01"

  common_tags = merge(var.tags, {
    managed-by  = "terraform"
    environment = var.env
    module      = "key-vault"
  })
}

data "azurerm_client_config" "current" {}

# ---------------------------------------------------------------------------
# Key Vault
# ---------------------------------------------------------------------------

resource "azurerm_key_vault" "this" {
  name                = "kv-${local.name_suffix}"
  location            = var.location
  resource_group_name = var.resource_group_name
  tenant_id           = var.tenant_id
  sku_name            = var.sku_name

  # Use RBAC instead of legacy access policies
  enable_rbac_authorization = true

  soft_delete_retention_days = var.soft_delete_retention_days
  purge_protection_enabled   = var.env == "prod" ? true : false

  tags = local.common_tags
}

# ---------------------------------------------------------------------------
# RBAC: Secrets Officer for operators / service principals
# ---------------------------------------------------------------------------

resource "azurerm_role_assignment" "operator_secrets_officer" {
  for_each = toset(var.operator_object_ids)

  scope                = azurerm_key_vault.this.id
  role_definition_name = "Key Vault Secrets Officer"
  principal_id         = each.value
}

# ---------------------------------------------------------------------------
# RBAC: Secrets User for agent VM Managed Identities (read-only)
# ---------------------------------------------------------------------------

resource "azurerm_role_assignment" "vm_secrets_user" {
  for_each = toset(var.vm_principal_ids)

  scope                = azurerm_key_vault.this.id
  role_definition_name = "Key Vault Secrets User"
  principal_id         = each.value
}

# ---------------------------------------------------------------------------
# Placeholder secrets
# Populated by humans after apply. The pipeline variable groups reference
# these via the Key Vault linked secret integration in Azure DevOps.
# ---------------------------------------------------------------------------

resource "azurerm_key_vault_secret" "ado_pat" {
  name         = "ado-pat"
  value        = "REPLACE-ME"
  key_vault_id = azurerm_key_vault.this.id

  tags = {
    description = "Azure DevOps PAT for self-hosted agent registration. Replace after apply."
  }

  lifecycle {
    # Ignore value changes — humans manage the actual secret value.
    ignore_changes = [value]
  }

  depends_on = [azurerm_role_assignment.operator_secrets_officer]
}

resource "azurerm_key_vault_secret" "vm_admin_password" {
  name         = "vm-admin-password"
  value        = "REPLACE-ME"
  key_vault_id = azurerm_key_vault.this.id

  tags = {
    description = "Agent VM local administrator password. Replaced by agent-vm module on first apply."
  }

  lifecycle {
    ignore_changes = [value]
  }

  depends_on = [azurerm_role_assignment.operator_secrets_officer]
}
